import type { Question } from "./types"

export const questions: Question[] = [
  {
    id: 1,
    question: "How do you handle being left on read? 👻",
    options: [
      {
        text: "Send multiple follow-up texts asking if they're okay",
        maleText: "Send 47 follow-up texts asking if she's okay",
        femaleText: "Send 47 follow-up texts asking if he's okay",
        redFlags: 3,
        yellowFlags: 0,
        greenFlags: 0,
      },
      { text: "Wait patiently like a normal human being", redFlags: 0, yellowFlags: 0, greenFlags: 2 },
      { text: "Screenshot and send to the group chat immediately", redFlags: 1, yellowFlags: 1, greenFlags: 0 },
      {
        text: "Show up at their place with snacks",
        maleText: "Show up at her place with snacks",
        femaleText: "Show up at his place with snacks",
        redFlags: 5,
        yellowFlags: 0,
        greenFlags: 0,
      },
    ],
  },
  {
    id: 2,
    maleQuestion: "Your ex texts you 'hey' at 2 AM. You:",
    femaleQuestion: "Your ex texts you 'hey' at 2 AM. You:",
    question: "Your ex texts you 'hey' at 2 AM. You:",
    options: [
      { text: "Reply instantly because you never deleted their number", redFlags: 2, yellowFlags: 1, greenFlags: 0 },
      {
        text: "Leave them on read like the queen/king you are",
        maleText: "Leave her on read like the king you are",
        femaleText: "Leave him on read like the queen you are",
        redFlags: 0,
        yellowFlags: 0,
        greenFlags: 2,
      },
      { text: "Send a 3-paragraph essay about closure", redFlags: 3, yellowFlags: 0, greenFlags: 0 },
      { text: "Forward it to your current partner for laughs", redFlags: 0, yellowFlags: 1, greenFlags: 1 },
    ],
  },
  {
    id: 3,
    maleQuestion: "How do you handle your girl talking to her ex? 🔥",
    femaleQuestion: "How do you handle your man talking to his ex? 🔥",
    question: "How do you handle your partner talking to their ex? 🔥",
    options: [
      {
        text: "Stalk their ex's entire social media history",
        maleText: "Stalk her ex's entire social media history",
        femaleText: "Stalk his ex's entire social media history",
        redFlags: 4,
        yellowFlags: 0,
        greenFlags: 0,
      },
      { text: "Trust them because you're not insecure", redFlags: 0, yellowFlags: 0, greenFlags: 3 },
      { text: "Ask casual questions while internally screaming", redFlags: 1, yellowFlags: 2, greenFlags: 0 },
      { text: "Demand they block everyone they've ever dated", redFlags: 5, yellowFlags: 0, greenFlags: 0 },
    ],
  },
  {
    id: 4,
    maleQuestion: "Your dating app bio says:",
    femaleQuestion: "Your dating app bio says:",
    question: "Your dating app bio says:",
    options: [
      {
        text: "Looking for my partner in crime 🔫",
        maleText: "Looking for my ride or die queen 🔫",
        femaleText: "Looking for my partner in crime 🔫",
        redFlags: 1,
        yellowFlags: 1,
        greenFlags: 0,
      },
      { text: "No drama, good vibes only ✨", redFlags: 0, yellowFlags: 0, greenFlags: 1 },
      {
        text: "If you can't handle me at my worst...",
        maleText: "Alpha male seeking his queen",
        femaleText: "If you can't handle me at my worst...",
        redFlags: 3,
        yellowFlags: 0,
        greenFlags: 0,
      },
      { text: "Fluent in sarcasm, PhD in overthinking", redFlags: 2, yellowFlags: 1, greenFlags: 0 },
    ],
  },
  {
    id: 5,
    question: "First date location preference? 📍",
    options: [
      {
        text: "Somewhere expensive so they prove their worth",
        maleText: "Somewhere expensive to show you're a provider",
        femaleText: "Somewhere expensive so he proves his worth",
        redFlags: 2,
        yellowFlags: 1,
        greenFlags: 0,
      },
      { text: "Coffee shop - casual and public", redFlags: 0, yellowFlags: 0, greenFlags: 2 },
      {
        text: "Their place because you're 'different'",
        maleText: "Her place because you're 'not like other guys'",
        femaleText: "His place because you're 'not like other girls'",
        redFlags: 3,
        yellowFlags: 0,
        greenFlags: 0,
      },
      { text: "Escape room to test their problem-solving skills", redFlags: 1, yellowFlags: 0, greenFlags: 1 },
    ],
  },
  {
    id: 6,
    question: "How do you handle arguments? 💥",
    options: [
      { text: "Bring up everything they've done wrong since 2019", redFlags: 4, yellowFlags: 0, greenFlags: 0 },
      { text: "Take time to cool down then discuss calmly", redFlags: 0, yellowFlags: 0, greenFlags: 3 },
      {
        text: "Give them the silent treatment until they apologize",
        maleText: "Give her the silent treatment until she apologizes",
        femaleText: "Give him the silent treatment until he apologizes",
        redFlags: 3,
        yellowFlags: 0,
        greenFlags: 0,
      },
      { text: "Cry until they feel bad and give in", redFlags: 2, yellowFlags: 1, greenFlags: 0 },
    ],
  },
  {
    id: 7,
    maleQuestion: "Your girl's phone buzzes. You:",
    femaleQuestion: "Your man's phone buzzes. You:",
    question: "Your partner's phone buzzes. You:",
    options: [
      { text: "Casually glance to see who's texting", redFlags: 1, yellowFlags: 1, greenFlags: 0 },
      { text: "Mind your own business like an adult", redFlags: 0, yellowFlags: 0, greenFlags: 2 },
      { text: "Memorize their passcode for future investigations", redFlags: 5, yellowFlags: 0, greenFlags: 0 },
      { text: "Ask who it is in a totally not suspicious way", redFlags: 2, yellowFlags: 0, greenFlags: 0 },
    ],
  },
  {
    id: 8,
    question: "Social media relationship status? 📱",
    options: [
      { text: "Post couple pics daily with cringe captions", redFlags: 2, yellowFlags: 1, greenFlags: 0 },
      { text: "Occasional cute posts, nothing excessive", redFlags: 0, yellowFlags: 0, greenFlags: 1 },
      { text: "Keep it private until you're sure they're 'the one'", redFlags: 0, yellowFlags: 1, greenFlags: 1 },
      {
        text: "Tag them in every meme and TikTok",
        maleText: "Tag her in every meme and TikTok",
        femaleText: "Tag him in every meme and TikTok",
        redFlags: 1,
        yellowFlags: 1,
        greenFlags: 0,
      },
    ],
  },
  {
    id: 9,
    maleQuestion: "How do you handle her friends? 👥",
    femaleQuestion: "How do you handle his friends? 👥",
    question: "How do you handle your partner's friends? 👥",
    options: [
      { text: "Become besties with all of them immediately", redFlags: 1, yellowFlags: 1, greenFlags: 0 },
      { text: "Be friendly but maintain your own friend group", redFlags: 0, yellowFlags: 0, greenFlags: 2 },
      { text: "Secretly hate them all but smile politely", redFlags: 2, yellowFlags: 1, greenFlags: 0 },
      { text: "Convince your partner they're all toxic", redFlags: 4, yellowFlags: 0, greenFlags: 0 },
    ],
  },
  {
    id: 10,
    question: "Red flag in others that you definitely don't have:",
    options: [
      { text: "Being too clingy and needy", redFlags: 2, yellowFlags: 0, greenFlags: 0 },
      { text: "Poor communication skills", redFlags: 1, yellowFlags: 1, greenFlags: 0 },
      { text: "Trust issues and jealousy", redFlags: 3, yellowFlags: 0, greenFlags: 0 },
      { text: "Actually, I'm pretty self-aware about my flaws", redFlags: 0, yellowFlags: 0, greenFlags: 3 },
    ],
  },
  // Additional questions for variety
  {
    id: 11,
    question: "Your ideal weekend with your partner:",
    options: [
      { text: "Netflix and chill without phones", redFlags: 0, yellowFlags: 0, greenFlags: 2 },
      { text: "Double date with friends to show them off", redFlags: 1, yellowFlags: 1, greenFlags: 0 },
      { text: "Stay in bed all day and ignore the world", redFlags: 2, yellowFlags: 0, greenFlags: 0 },
      { text: "Plan every hour with activities and photos", redFlags: 2, yellowFlags: 1, greenFlags: 0 },
    ],
  },
  {
    id: 12,
    maleQuestion: "She's going out with her girls. You:",
    femaleQuestion: "He's going out with his boys. You:",
    question: "Your partner's going out with friends. You:",
    options: [
      { text: "Encourage them to have fun and check in later", redFlags: 0, yellowFlags: 0, greenFlags: 3 },
      { text: "Ask for location updates every hour", redFlags: 3, yellowFlags: 0, greenFlags: 0 },
      { text: "Sulk because they chose friends over you", redFlags: 4, yellowFlags: 0, greenFlags: 0 },
      { text: "Use the time for your own hobbies", redFlags: 0, yellowFlags: 0, greenFlags: 2 },
    ],
  },
  {
    id: 13,
    question: "Your partner forgot your anniversary. You:",
    options: [
      { text: "Calmly remind them and plan something together", redFlags: 0, yellowFlags: 0, greenFlags: 2 },
      { text: "Give them the silent treatment for a week", redFlags: 3, yellowFlags: 0, greenFlags: 0 },
      { text: "Post passive-aggressive stories on social media", redFlags: 4, yellowFlags: 0, greenFlags: 0 },
      { text: "Bring it up in every future argument", redFlags: 5, yellowFlags: 0, greenFlags: 0 },
    ],
  },
  {
    id: 14,
    question: "How do you handle your partner's hobbies?",
    options: [
      { text: "Support them even if you don't understand", redFlags: 0, yellowFlags: 0, greenFlags: 3 },
      { text: "Try to get involved in everything they do", redFlags: 2, yellowFlags: 1, greenFlags: 0 },
      { text: "Complain that they spend too much time on it", redFlags: 3, yellowFlags: 0, greenFlags: 0 },
      { text: "Make fun of their interests", redFlags: 5, yellowFlags: 0, greenFlags: 0 },
    ],
  },
  {
    id: 15,
    maleQuestion: "She's talking to a male coworker. You:",
    femaleQuestion: "He's talking to a female coworker. You:",
    question: "Your partner's talking to an attractive coworker. You:",
    options: [
      { text: "Trust them completely", redFlags: 0, yellowFlags: 0, greenFlags: 3 },
      { text: "Ask casual questions about the coworker", redFlags: 1, yellowFlags: 1, greenFlags: 0 },
      { text: "Show up at their workplace unexpectedly", redFlags: 4, yellowFlags: 0, greenFlags: 0 },
      { text: "Demand they find a new job", redFlags: 5, yellowFlags: 0, greenFlags: 0 },
    ],
  },
  {
    id: 16,
    question: "Your partner wants alone time. You:",
    options: [
      { text: "Respect their space and do your own thing", redFlags: 0, yellowFlags: 0, greenFlags: 3 },
      { text: "Ask what you did wrong", redFlags: 2, yellowFlags: 1, greenFlags: 0 },
      { text: "Assume they're planning to break up", redFlags: 3, yellowFlags: 0, greenFlags: 0 },
      { text: "Follow them around until they explain", redFlags: 4, yellowFlags: 0, greenFlags: 0 },
    ],
  },
  {
    id: 17,
    question: "Your partner's family doesn't like you. You:",
    options: [
      { text: "Try to understand their perspective and improve", redFlags: 0, yellowFlags: 0, greenFlags: 2 },
      { text: "Avoid family gatherings completely", redFlags: 1, yellowFlags: 2, greenFlags: 0 },
      { text: "Make your partner choose between you and them", redFlags: 5, yellowFlags: 0, greenFlags: 0 },
      { text: "Talk badly about them to your partner", redFlags: 4, yellowFlags: 0, greenFlags: 0 },
    ],
  },
  {
    id: 18,
    question: "You find out your partner lied about something small:",
    options: [
      { text: "Have a calm conversation about honesty", redFlags: 0, yellowFlags: 0, greenFlags: 2 },
      { text: "Question everything they've ever told you", redFlags: 3, yellowFlags: 0, greenFlags: 0 },
      { text: "Give them the benefit of the doubt", redFlags: 0, yellowFlags: 1, greenFlags: 1 },
      { text: "Start lying to them in return", redFlags: 4, yellowFlags: 0, greenFlags: 0 },
    ],
  },
  {
    id: 19,
    maleQuestion: "She's having a bad day. You:",
    femaleQuestion: "He's having a bad day. You:",
    question: "Your partner's having a bad day. You:",
    options: [
      { text: "Listen and offer support without trying to fix everything", redFlags: 0, yellowFlags: 0, greenFlags: 3 },
      { text: "Try to cheer them up with jokes", redFlags: 0, yellowFlags: 1, greenFlags: 1 },
      { text: "Get frustrated that they're bringing you down", redFlags: 3, yellowFlags: 0, greenFlags: 0 },
      { text: "Make it about yourself and your problems", redFlags: 4, yellowFlags: 0, greenFlags: 0 },
    ],
  },
  {
    id: 20,
    question: "Your partner gains weight. You:",
    options: [
      { text: "Love them exactly the same", redFlags: 0, yellowFlags: 0, greenFlags: 3 },
      { text: "Suggest working out together", redFlags: 0, yellowFlags: 1, greenFlags: 1 },
      { text: "Make subtle comments about their eating", redFlags: 3, yellowFlags: 0, greenFlags: 0 },
      { text: "Lose attraction and consider leaving", redFlags: 5, yellowFlags: 0, greenFlags: 0 },
    ],
  },
  {
  id: 21,
  maleQuestion: "She takes hours to reply but is still posting stories.",
  femaleQuestion: "He takes hours to reply but is still posting stories.",
  question: "Your partner’s replying late but clearly active online.",
  options: [
    { text: "Send a '👍' and mentally check out", redFlags: 1, yellowFlags: 1, greenFlags: 0 },
    { text: "Double-text with 'are you ignoring me?'", redFlags: 3, yellowFlags: 0, greenFlags: 0 },
    { text: "Respect their space — everyone’s busy sometimes", redFlags: 0, yellowFlags: 0, greenFlags: 2 },
    { text: "Watch all their stories like it’s a documentary", redFlags: 2, yellowFlags: 1, greenFlags: 0 },
  ],
},
{
  id: 23,
  maleQuestion: "She tells you, 'We need to talk later.'",
  femaleQuestion: "He tells you, 'We need to talk later.'",
  question: "Your partner says they want to talk later. What’s your reaction?",
  options: [
    { text: "Panic, spiral, and write your emotional will", redFlags: 3, yellowFlags: 0, greenFlags: 0 },
    { text: "Reply: 'okay no problem 😊' and mean it", redFlags: 0, yellowFlags: 0, greenFlags: 3 },
    { text: "Send 9 texts asking if you’re in trouble", redFlags: 2, yellowFlags: 1, greenFlags: 0 },
    { text: "Call them 3 times because you’re not built for suspense", redFlags: 4, yellowFlags: 0, greenFlags: 0 },
  ],
},
{
  id: 25,
  maleQuestion: "You and your girl just had your first fight.",
  femaleQuestion: "You and your man just had your first fight.",
  question: "The first argument hits different. What do you do?",
  options: [
    { text: "Talk it out like adults (or try your best)", redFlags: 0, yellowFlags: 0, greenFlags: 3 },
    { text: "Block, unblock, then send a long paragraph", redFlags: 3, yellowFlags: 0, greenFlags: 0 },
    { text: "Start tweeting vague quotes about loyalty", redFlags: 4, yellowFlags: 0, greenFlags: 0 },
    { text: "Apologize first, even if you’re not sure why", redFlags: 0, yellowFlags: 1, greenFlags: 1 },
  ],
},

]
